pipeline: 
  python_build: 
    commands: 
      - "pip install coverage" #can be mentioned in requirements.txt
      - "pip install pytest"
      - "coverage run --source=example-py-pytest/com/automationpanda/example example-py-pytest/tests/test*.py"
      - "coverage xml"
    image: frolvlad/alpine-python3
  docker build push:
    image: plugins/docker
    repo: chashruti/drone1.0/drone-test
    #registry: https://cloud.docker.com
    tags:
        - latest
    #secrets: [ docker_username, docker_password ]
    environment:
     # repo: chashruti/drone1.0/drone-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      #tags:
       # - latest
    #secrets: [ docker_username, docker_password ]
    when:
      event: [push]  
  

