pipeline: 
  python_build: 
    commands: 
      - "pip install coverage" #can be mentioned in requirements.txt
      - "pip install pytest" #can be mentioned in requirements.txt
      #- "pip install -r requirements.txt"
      - "coverage run --source=example-py-pytest/com/automationpanda/example example-py-pytest/tests/test*.py"
      - "coverage xml"
    image: frolvlad/alpine-python3
    when:
      event: [push]
  docker_build_push:
    image: plugins/docker
    repo: chashruti/drone1.0/drone-test
    tags:
        - latest
    environment:
     # repo: chashruti/drone1.0/drone-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    #secrets: [ docker_username, docker_password ]
    when:
      event: [push]    
